[tool.poetry]
name = "testman"
version = "0.1.0"
description = "None"
authors = ["XuanBo"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
setuptools = "^75.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
